'use client';

import React from 'react';
import { KeyAffordance } from './KeyAffordance';
import { STATUS_ICONS, STATUS_TITLE } from '@/lib/taskStatusIcons';
import { PRIORITY_ICONS, PRIORITY_TITLE } from '@/lib/taskPriorityIcons';
import type { PropertyOccupancy } from '@/lib/types';

// Shared row + visual constants used across task-list surfaces (My Assignments,
// Property Tasks, and anywhere else we render the "status marble" list design).
//
// Every consumer should render rows through <TaskRow /> so visual changes
// propagate uniformly. Grouping, filtering, sorting, and detail-panel wiring
// stay per-consumer (each surface has its own rules for what "due" means).

// ---- Types -----------------------------------------------------------------

export interface TaskRowAssignee {
  user_id: string;
  name: string;
  avatar: string | null;
}

export interface TaskRowItem {
  // Stable key, must be unique within a list.
  key: string;
  title: string;
  property_name?: string | null;
  status: string;
  priority: string;
  department_id?: string | null;
  department_name?: string | null;
  scheduled_date?: string | null;
  scheduled_time?: string | null;
  assignees: TaskRowAssignee[];
  // Optional ledger metadata. When provided + the corresponding show flag is
  // on, the row renders inline indicators.
  bin_id?: string | null;
  bin_name?: string | null;
  is_binned?: boolean;
  // True when the task was generated by automation (reservation turnovers,
  // recurring rules, templated spawns). False when created manually via the
  // "New Task" button. Used by the ledger Manual/Automated origin filter.
  is_automated?: boolean;
  // Foreign key to the linked reservation when present. The presence of this
  // (not is_automated) is what drives the small "key" badge next to the
  // title — it's the rows that will be re-dated by the recalibration trigger
  // when a reservation moves. Recurring tasks have is_automated=true but
  // reservation_id=null, so they do NOT show the badge.
  reservation_id?: string | null;
  // Total number of comments on this task. Rendered in the comments column.
  comment_count?: number;
  // Live occupancy of this task's property, as of now. Null when the task has
  // no property (nothing to be occupied) or when the surface doesn't supply it.
  // Rendered only when the consumer passes `showOccupancy`.
  occupancy?: PropertyOccupancy | null;
}

// ---- Status + priority visual constants ------------------------------------
// Exported so consumers can render matching legends / filter chips.

export const STATUS_COLORS: Record<string, string> = {
  not_started: '#A78BFA',
  in_progress: '#6366F1',
  paused: '#8B7FA8',
  complete: '#4C4869',
};

export const STATUS_MARBLE: Record<string, string> = {
  not_started:
    'radial-gradient(ellipse at 25% 35%, rgba(255,255,255,0.35) 0%, transparent 50%), radial-gradient(ellipse at 70% 20%, rgba(255,255,255,0.2) 0%, transparent 45%), linear-gradient(155deg, rgba(255,255,255,0.18) 10%, transparent 40%, rgba(255,255,255,0.12) 75%), radial-gradient(ellipse at 50% 80%, rgba(0,0,0,0.08) 0%, transparent 55%), #A78BFA',
  in_progress:
    'radial-gradient(ellipse at 25% 35%, rgba(255,255,255,0.3) 0%, transparent 50%), radial-gradient(ellipse at 70% 20%, rgba(255,255,255,0.18) 0%, transparent 45%), linear-gradient(155deg, rgba(255,255,255,0.15) 10%, transparent 40%, rgba(255,255,255,0.1) 75%), radial-gradient(ellipse at 50% 80%, rgba(0,0,0,0.1) 0%, transparent 55%), #6366F1',
  paused:
    'radial-gradient(ellipse at 25% 35%, rgba(255,255,255,0.3) 0%, transparent 50%), radial-gradient(ellipse at 70% 20%, rgba(255,255,255,0.2) 0%, transparent 45%), linear-gradient(155deg, rgba(255,255,255,0.15) 10%, transparent 40%, rgba(255,255,255,0.1) 75%), radial-gradient(ellipse at 50% 80%, rgba(0,0,0,0.08) 0%, transparent 55%), #8B7FA8',
  complete:
    'radial-gradient(ellipse at 25% 35%, rgba(255,255,255,0.25) 0%, transparent 50%), radial-gradient(ellipse at 70% 20%, rgba(255,255,255,0.15) 0%, transparent 45%), linear-gradient(155deg, rgba(255,255,255,0.12) 10%, transparent 40%, rgba(255,255,255,0.08) 75%), radial-gradient(ellipse at 50% 80%, rgba(0,0,0,0.1) 0%, transparent 55%), #4C4869',
};

export const STATUS_LABELS: Record<string, string> = {
  not_started: 'Not started',
  in_progress: 'In progress',
  paused: 'Paused',
  complete: 'Complete',
};

export const PRIORITY_LABELS: Record<string, string> = {
  urgent: 'Urgent',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

// ---- Small sub-components --------------------------------------------------

export function PriorityTag({ priority }: { priority: string }) {
  if (!priority || priority === 'low') return null;
  const colorClass =
    priority === 'urgent'
      ? 'text-red-500 dark:text-[#d97757]'
      : priority === 'high'
      ? 'text-neutral-800 dark:text-[#f0efed]'
      : 'text-neutral-500 dark:text-[#a09e9a]';
  const PriorityIcon = PRIORITY_ICONS[priority] ?? PRIORITY_ICONS.medium;
  return (
    <span
      className={`inline-flex items-center gap-1 text-[11px] tracking-[0.02em] font-medium pl-2 border-l border-neutral-200 dark:border-[rgba(255,255,255,0.07)] ${colorClass}`}
      title={PRIORITY_TITLE[priority] ?? priority}
    >
      <PriorityIcon size={12} strokeWidth={2} aria-hidden />
      {PRIORITY_LABELS[priority] || priority}
    </span>
  );
}

// ---- Occupancy -------------------------------------------------------------

/**
 * Tailwind text color per occupancy state. Shared by desktop + mobile rows.
 *
 * Only the exceptional state carries color. Occupied and vacant are both
 * routine — every property is one or the other at all times — so they read in
 * the row's neutral text and let the word do the work.
 */
export const OCCUPANCY_TEXT_CLASS: Record<string, string> = {
  occupied: 'text-neutral-500 dark:text-[#a09e9a]',
  // Blocked matches the urgent-priority red used elsewhere in the row — it's
  // the state most likely to derail a scheduled visit.
  blocked: 'text-red-500 dark:text-[#d97757]',
  vacant: 'text-neutral-500 dark:text-[#a09e9a]',
};

export const OCCUPANCY_LABELS: Record<string, string> = {
  occupied: 'Occupied',
  blocked: 'Blocked',
  vacant: 'Vacant',
};

/**
 * Render a wall-clock "HH:MM" as a compact clock label: 10:00 → "10am",
 * 16:00 → "4pm", 15:30 → "3:30pm". The on-the-hour case drops ":00" because
 * check-in/check-out times almost always land there and the minutes are noise.
 */
export function formatClock(time: string): string {
  const [h, m] = time.split(':').map(Number);
  if (!Number.isFinite(h)) return time;
  const meridiem = h >= 12 ? 'pm' : 'am';
  const hour12 = h % 12 || 12;
  return m ? `${hour12}:${String(m).padStart(2, '0')}${meridiem}` : `${hour12}${meridiem}`;
}

/**
 * Turn an occupancy snapshot into the two strings a row renders. Shared so the
 * desktop column and the mobile footer line can never drift in wording.
 *
 * `detail` states how long the CURRENT state holds — "until 10am Aug 1" — with
 * the time carried all the way through. On a same-day flip the unit empties at
 * checkout and refills that afternoon, so a date alone ("until Aug 1") would be
 * ambiguous about the only window anyone can actually work in.
 */
export function formatOccupancy(
  occupancy: PropertyOccupancy | null | undefined
): { label: string; detail: string | null } | null {
  if (!occupancy) return null;
  const label = OCCUPANCY_LABELS[occupancy.status] ?? occupancy.status;
  if (!occupancy.until) {
    // Nothing scheduled inside the horizon. Only worth saying out loud when the
    // property is free — "occupied with no end in sight" is a data smell, not a
    // fact worth surfacing on a task row.
    return {
      label,
      detail: occupancy.status === 'vacant' ? 'No future bookings' : null,
    };
  }
  const [date, time] = occupancy.until.split('T');
  const d = getShortDate(date);
  if (!d) return { label, detail: null };
  // Midnight is a whole-day boundary (calendar blocks), not a real clock time —
  // "until 12am Sep 27" is noise, "until Sep 27" is the fact.
  const clock = time && time !== '00:00' ? `${formatClock(time)} ` : '';
  return { label, detail: `Until ${clock}${d.month} ${d.day}` };
}

/** Tooltip text spelling out the same fact in a full sentence. */
export function occupancyTitle(
  occupancy: PropertyOccupancy | null | undefined
): string | undefined {
  if (!occupancy) return undefined;
  const base =
    occupancy.status === 'occupied'
      ? 'Someone is in the unit'
      : occupancy.status === 'blocked'
      ? 'Blocked on the calendar — no guest'
      : 'Nobody in the unit';
  if (!occupancy.until) {
    return `${base} — nothing scheduled in the next few months.`;
  }
  const [date, time] = occupancy.until.split('T');
  const d = getShortDate(date);
  const when = `${time && time !== '00:00' ? `${formatClock(time)} ` : ''}${
    d ? `${d.month} ${d.day}` : date
  }`;
  const verb =
    occupancy.until_kind === 'free'
      ? 'Free from'
      : occupancy.until_kind === 'booked'
      ? 'Next guest arrives'
      : 'Blocked from';
  return `${base}. ${verb} ${when} (${occupancy.timezone}).`;
}

// Archive-drawer icon — matches the bin iconography in
// `components/windows/projects/BinPicker.tsx` (the "Task Bin" card).
export function BinIcon({ className = 'w-3 h-3' }: { className?: string }) {
  return (
    <svg
      className={className}
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
      />
    </svg>
  );
}

// Speech-bubble icon for the comments column.
export function CommentIcon({ className = 'w-3 h-3' }: { className?: string }) {
  return (
    <svg
      className={className}
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M7 8h10M7 12h6m-6 8a8 8 0 110-16 8 8 0 014 14.9L7 20z"
      />
    </svg>
  );
}

// ---- Date / time formatting helpers ----------------------------------------

export function formatTimeCol(timeString?: string | null): {
  time: string;
  meridiem: string;
} | null {
  if (!timeString) return null;
  const [h, m] = timeString.split(':').map(Number);
  const ampm = h >= 12 ? 'PM' : 'AM';
  const hour12 = h % 12 || 12;
  return { time: `${hour12}:${String(m).padStart(2, '0')}`, meridiem: ampm };
}

export function getDayLabel(dateStr?: string | null): string | null {
  if (!dateStr) return null;
  const date = new Date(dateStr + 'T00:00:00');
  return date.toLocaleDateString('en-US', { weekday: 'short' }).toUpperCase();
}

export function getShortDate(
  dateStr?: string | null
): { month: string; day: number } | null {
  if (!dateStr) return null;
  const date = new Date(dateStr + 'T00:00:00');
  const month = date.toLocaleDateString('en-US', { month: 'short' });
  return { month, day: date.getDate() };
}

// ---- TaskListHeader --------------------------------------------------------
// Column labels aligned with the TaskRow grid. Render once at the top of a
// task list (before the group headers) to label the assignee / department /
// bin / comments columns. Italic lowercase to feel annotative rather than
// table-like.

// Static class portion shared by the header and every row. The dynamic
// piece (grid-template-columns) is set inline via `taskRowGridTemplateColumns`
// because Tailwind's JIT can't reliably synthesize arbitrary-value
// class names from runtime-built strings.
const TASK_ROW_GRID_CLASS = 'grid gap-4 px-3 -mx-3';

// Single source of truth for column geometry, in px. Every entry but `task` is
// a fixed width; `task` is a FLOOR the flexible column may grow above.
const TASK_ROW_COLUMNS = {
  when: 56,
  task: 280,
  occupancy: 132,
  assignee: 96,
  department: 120,
  bin: 128,
  comments: 56,
} as const;

/** Tailwind `gap-4`, needed to compute the row's total minimum width. */
const TASK_ROW_GAP = 16;

interface TaskListColumnOpts {
  hideDepartment?: boolean;
  hideBin?: boolean;
  hideComments?: boolean;
  // Occupancy is opt-in rather than opt-out: only surfaces whose payload
  // actually carries an occupancy snapshot should reserve the column, so every
  // other task list keeps its current layout untouched.
  showOccupancy?: boolean;
  // Give the task column a minimum width so the row keeps its proportions on a
  // narrow viewport instead of compressing until content wraps — the grid grows
  // past the container and the list scrolls horizontally.
  //
  // Opt-in, because it only works if the CONSUMER also supplies a horizontally
  // scrollable container (see MyAssignmentsWindow); switching it on without one
  // would just clip. Consumers that opt in should size their content wrapper
  // with `taskRowMinWidth()` so section headers span the scrollable width too.
  lockColumnWidths?: boolean;
}

/** Widths of the columns actually rendered for `opts`, in grid order. */
function activeColumnWidths(opts: TaskListColumnOpts): number[] {
  return [
    TASK_ROW_COLUMNS.when,
    TASK_ROW_COLUMNS.task,
    opts.showOccupancy ? TASK_ROW_COLUMNS.occupancy : 0,
    TASK_ROW_COLUMNS.assignee,
    opts.hideDepartment ? 0 : TASK_ROW_COLUMNS.department,
    opts.hideBin ? 0 : TASK_ROW_COLUMNS.bin,
    opts.hideComments ? 0 : TASK_ROW_COLUMNS.comments,
  ].filter((w) => w > 0);
}

export function taskRowGridTemplateColumns(opts: TaskListColumnOpts = {}): string {
  return [
    `${TASK_ROW_COLUMNS.when}px`,
    opts.lockColumnWidths
      ? `minmax(${TASK_ROW_COLUMNS.task}px,1fr)`
      : 'minmax(0,1fr)',
    opts.showOccupancy ? `${TASK_ROW_COLUMNS.occupancy}px` : null,
    `${TASK_ROW_COLUMNS.assignee}px`,
    opts.hideDepartment ? null : `${TASK_ROW_COLUMNS.department}px`,
    opts.hideBin ? null : `${TASK_ROW_COLUMNS.bin}px`,
    opts.hideComments ? null : `${TASK_ROW_COLUMNS.comments}px`,
  ]
    .filter(Boolean)
    .join(' ');
}

/**
 * The narrowest a locked row can be, in px — every column at its floor plus the
 * gaps between them. Consumers apply this to the wrapper holding the header,
 * section headers and rows so all three span the same scrollable width.
 *
 * Deliberately NOT `w-max`: the task column is a `1fr` track, and under
 * max-content sizing a single long title would blow the whole list out to that
 * title's width instead of truncating.
 */
export function taskRowMinWidth(opts: TaskListColumnOpts = {}): number {
  const widths = activeColumnWidths(opts);
  return widths.reduce((sum, w) => sum + w, 0) + (widths.length - 1) * TASK_ROW_GAP;
}

export function TaskListHeader({
  hideDepartment = false,
  hideBin = false,
  hideComments = false,
  showOccupancy = false,
  lockColumnWidths = false,
}: TaskListColumnOpts = {}) {
  return (
    <div
      className={`${TASK_ROW_GRID_CLASS} items-center pb-2 text-[10px] italic font-medium tracking-[0.02em] text-neutral-400 dark:text-[#66645f] select-none`}
      style={{
        gridTemplateColumns: taskRowGridTemplateColumns({
          hideDepartment,
          hideBin,
          hideComments,
          showOccupancy,
          lockColumnWidths,
        }),
      }}
    >
      <div className="text-right">when</div>
      <div>task</div>
      {showOccupancy && <div>occupancy</div>}
      <div>assignee</div>
      {!hideDepartment && <div>department</div>}
      {!hideBin && <div>bin</div>}
      {!hideComments && <div className="text-right">comments</div>}
    </div>
  );
}

// ---- TaskRow ---------------------------------------------------------------

interface TaskRowProps {
  item: TaskRowItem;
  selected?: boolean;
  isLast?: boolean;
  onClick?: () => void;
  // When the surrounding list is inherently about a single property, hide the
  // per-row property sub-label to reduce noise (every row would repeat it).
  hideProperty?: boolean;
  showBinPill?: boolean;
  // Column-level hides — drop the column entirely (header + body together
  // via the shared grid template). Used by narrow surfaces like the chat
  // attachment where the full 6-column layout doesn't fit.
  hideDepartment?: boolean;
  hideBin?: boolean;
  hideComments?: boolean;
  // Opt in to the occupancy column. Must match the <TaskListHeader> above the
  // list, since both derive their columns from the same grid template.
  showOccupancy?: boolean;
  // Floor the task column's width — see TaskListColumnOpts. Must also match the
  // <TaskListHeader> above the list.
  lockColumnWidths?: boolean;
  // Optional department icon (rendered at the row's top-right).
  departmentIcon?: React.ComponentType<{ className?: string }>;
}

// Shared avatar stack used in the assignee column.
function AssigneeStack({ assignees }: { assignees: TaskRowAssignee[] }) {
  if (assignees.length === 0) {
    return (
      <span className="text-[12px] text-neutral-300 dark:text-[#3e3d3a] font-medium">
        —
      </span>
    );
  }
  return (
    <div className="flex">
      {assignees.slice(0, 3).map((u, i) => (
        <div
          key={u.user_id}
          className="w-[26px] h-[26px] rounded-full bg-neutral-200 dark:bg-neutral-700 flex items-center justify-center text-[10px] font-semibold text-neutral-600 dark:text-[#a09e9a] overflow-hidden ring-2 ring-white dark:ring-background"
          style={{ marginLeft: i > 0 ? '-8px' : 0 }}
          title={u.name}
        >
          {u.avatar ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={u.avatar}
              alt={u.name}
              className="w-full h-full object-cover"
            />
          ) : (
            u.name
              .split(' ')
              .map((n) => n[0])
              .join('')
              .slice(0, 2)
              .toUpperCase()
          )}
        </div>
      ))}
      {assignees.length > 3 && (
        <div
          className="w-[26px] h-[26px] rounded-full bg-neutral-100 dark:bg-[#2a2825] flex items-center justify-center text-[10px] font-semibold text-neutral-500 dark:text-[#a09e9a] ring-2 ring-white dark:ring-background"
          style={{ marginLeft: '-8px' }}
          title={`+${assignees.length - 3} more`}
        >
          +{assignees.length - 3}
        </div>
      )}
    </div>
  );
}

// Occupancy column — state on top, what-happens-next underneath in italics,
// matching the annotative treatment the mobile row uses. Sized to the property
// sub-label (12px) so the two read as the same class of information, and
// vertically centred with the columns to its right rather than pinned to the
// title's baseline.
function OccupancyCell({ occupancy }: { occupancy?: PropertyOccupancy | null }) {
  const formatted = formatOccupancy(occupancy);
  if (!formatted || !occupancy) return <EmDash />;
  return (
    // The detail line is positioned OUT of flow so the cell's measured height is
    // just the state label. The grid's items-center then puts that label on the
    // same line as the single-line department and bin columns, instead of
    // centring the two-line block and leaving the label riding above them.
    <div className="min-w-0 w-full relative" title={occupancyTitle(occupancy)}>
      <div
        className={`text-[12px] font-medium tracking-[0.02em] truncate ${
          OCCUPANCY_TEXT_CLASS[occupancy.status] ?? OCCUPANCY_TEXT_CLASS.vacant
        }`}
      >
        {formatted.label}
      </div>
      {formatted.detail && (
        <div className="absolute left-0 top-full w-full text-[12px] italic text-neutral-400 dark:text-[#66645f] leading-snug tracking-tight truncate mt-0.5">
          {formatted.detail}
        </div>
      )}
    </div>
  );
}

// Empty placeholder used when a column has no value to show.
function EmDash() {
  return (
    <span className="text-[12px] text-neutral-300 dark:text-[#3e3d3a] font-medium">
      —
    </span>
  );
}

export function TaskRow({
  item,
  selected = false,
  isLast = false,
  onClick,
  hideProperty = false,
  showBinPill = false,
  hideDepartment = false,
  hideBin = false,
  hideComments = false,
  showOccupancy = false,
  lockColumnWidths = false,
  departmentIcon: DeptIcon,
}: TaskRowProps) {
  const timeInfo = formatTimeCol(item.scheduled_time);
  const dayLabel = getDayLabel(item.scheduled_date);
  const shortDate = getShortDate(item.scheduled_date);
  const commentCount = item.comment_count ?? 0;

  return (
    <div
      role="button"
      tabIndex={0}
      onClick={onClick}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onClick?.();
        }
      }}
      className={`grid gap-4 py-3.5 text-left transition-colors items-center cursor-pointer ${
        selected
          ? 'bg-[rgba(30,25,20,0.04)] dark:bg-[rgba(255,255,255,0.04)]'
          : 'hover:bg-[rgba(30,25,20,0.02)] dark:hover:bg-[rgba(255,255,255,0.02)]'
      } ${
        !isLast
          ? 'border-b border-[rgba(30,25,20,0.08)] dark:border-[rgba(255,255,255,0.07)]'
          : ''
      } rounded-lg px-3 -mx-3`}
      style={{
        gridTemplateColumns: taskRowGridTemplateColumns({
          hideDepartment,
          hideBin,
          hideComments,
          showOccupancy,
          lockColumnWidths,
        }),
      }}
    >
      {/* Date/time column */}
      <div className="text-right pt-0.5 self-start">
        {item.scheduled_date || timeInfo ? (
          <>
            {shortDate && (
              <>
                {dayLabel && (
                  <div className="text-[9px] text-neutral-400 dark:text-[#66645f] uppercase tracking-[0.06em] font-medium mb-0.5">
                    {dayLabel}
                  </div>
                )}
                <div className="text-[12px] font-semibold text-neutral-800 dark:text-[#f0efed] leading-none tracking-tight whitespace-nowrap">
                  {shortDate.month} {shortDate.day}
                </div>
              </>
            )}
            {timeInfo && (
              <div className={item.scheduled_date ? 'mt-1' : ''}>
                <div className="text-[10px] font-medium text-neutral-400 dark:text-[#66645f] leading-none tracking-tight tabular-nums whitespace-nowrap">
                  {timeInfo.time}
                  {timeInfo.meridiem.toLowerCase()}
                </div>
              </div>
            )}
          </>
        ) : (
          <div className="text-[9px] text-neutral-300 dark:text-[#3e3d3a] uppercase tracking-[0.08em] font-medium leading-snug pt-0.5">
            no
            <br />
            date
          </div>
        )}
      </div>

      {/* Title + metadata row (status marble + label + priority) */}
      <div className="min-w-0 self-start">
        <div className="flex items-center gap-1.5 min-w-0 mb-0.5">
          <div className="text-[14px] font-medium text-neutral-800 dark:text-[#f0efed] leading-snug tracking-tight truncate min-w-0">
            {item.title}
          </div>
          <KeyAffordance reservationId={item.reservation_id} size={12} />

        </div>
        {!hideProperty && item.property_name && (
          <div className="text-[12px] text-neutral-500 dark:text-[#66645f] leading-snug truncate">
            {item.property_name}
          </div>
        )}
        <div className="flex items-center gap-2 mt-2">
          <span
            className="inline-flex items-center gap-1 text-[11px] tracking-[0.02em] font-medium"
            style={{ color: STATUS_COLORS[item.status] || '#A78BFA' }}
            title={STATUS_TITLE[item.status] ?? item.status}
          >
            {(() => {
              const StatusIcon =
                STATUS_ICONS[item.status] ?? STATUS_ICONS.not_started;
              return <StatusIcon size={12} strokeWidth={2} aria-hidden />;
            })()}
            {STATUS_LABELS[item.status] || item.status}
          </span>
          <PriorityTag priority={item.priority} />
        </div>
      </div>

      {/* Occupancy column */}
      {showOccupancy && (
        <div className="min-w-0 flex items-center">
          <OccupancyCell occupancy={item.occupancy} />
        </div>
      )}

      {/* Assignee column */}
      <div className="min-w-0 flex items-center">
        <AssigneeStack assignees={item.assignees} />
      </div>

      {/* Department column (icon + name) */}
      {!hideDepartment && (
        <div className="min-w-0 flex items-center gap-1.5 text-[12px] text-neutral-600 dark:text-[#a09e9a]">
          {DeptIcon && item.department_id ? (
            <>
              <DeptIcon className="w-[14px] h-[14px] text-neutral-400 dark:text-[#66645f] shrink-0" />
              <span className="truncate">
                {item.department_name || 'Department'}
              </span>
            </>
          ) : (
            <EmDash />
          )}
        </div>
      )}

      {/* Bin column */}
      {!hideBin && (
        <div className="min-w-0 flex items-center gap-1.5 text-[12px] text-neutral-600 dark:text-[#a09e9a]">
          {showBinPill && item.is_binned ? (
            <>
              <BinIcon className="w-[13px] h-[13px] text-neutral-400 dark:text-[#66645f] shrink-0" />
              <span className="truncate">{item.bin_name || 'Binned'}</span>
            </>
          ) : (
            <EmDash />
          )}
        </div>
      )}

      {/* Comments column */}
      {!hideComments && (
        <div
          className="flex items-center justify-end gap-1 text-[12px] tabular-nums text-neutral-500 dark:text-[#a09e9a]"
          title={`${commentCount} comment${commentCount === 1 ? '' : 's'}`}
        >
          <CommentIcon className="w-[13px] h-[13px] text-neutral-400 dark:text-[#66645f] shrink-0" />
          <span className={commentCount === 0 ? 'text-neutral-400 dark:text-[#66645f]' : ''}>
            {commentCount}
          </span>
        </div>
      )}
    </div>
  );
}
