import {
  Folder,
  Wrench,
  SprayCan,
  ClipboardCheck,
  Paintbrush,
  Truck,
  Shield,
  Flame,
  Droplets,
  Zap,
  Trees,
  Hammer,
  HardHat,
  ShowerHead,
  Bed,
  Sofa,
  Key,
  Lock,
  Wifi,
  ThermometerSun,
  Bug,
  Trash2,
  Package,
  Warehouse,
  Building2,
  Home,
  Star,
  Heart,
  type LucideIcon,
} from 'lucide-react';

// Map of icon keys to Lucide components
export const DEPARTMENT_ICON_MAP: Record<string, LucideIcon> = {
  folder: Folder,
  wrench: Wrench,
  'spray-can': SprayCan,
  'clipboard-check': ClipboardCheck,
  paintbrush: Paintbrush,
  truck: Truck,
  shield: Shield,
  flame: Flame,
  droplets: Droplets,
  zap: Zap,
  trees: Trees,
  hammer: Hammer,
  'hard-hat': HardHat,
  'shower-head': ShowerHead,
  bed: Bed,
  sofa: Sofa,
  key: Key,
  lock: Lock,
  wifi: Wifi,
  'thermometer-sun': ThermometerSun,
  bug: Bug,
  trash: Trash2,
  package: Package,
  warehouse: Warehouse,
  building: Building2,
  home: Home,
  star: Star,
  heart: Heart,
};

// Curated list for the icon picker with labels
export const DEPARTMENT_ICON_OPTIONS: Array<{ key: string; label: string }> = [
  { key: 'spray-can', label: 'Cleaning' },
  { key: 'wrench', label: 'Wrench' },
  { key: 'hammer', label: 'Hammer' },
  { key: 'clipboard-check', label: 'Inspection' },
  { key: 'paintbrush', label: 'Paint' },
  { key: 'hard-hat', label: 'Construction' },
  { key: 'droplets', label: 'Plumbing' },
  { key: 'zap', label: 'Electrical' },
  { key: 'flame', label: 'HVAC / Fire' },
  { key: 'thermometer-sun', label: 'Climate' },
  { key: 'shower-head', label: 'Bathroom' },
  { key: 'bed', label: 'Bedroom' },
  { key: 'sofa', label: 'Furniture' },
  { key: 'trees', label: 'Landscaping' },
  { key: 'bug', label: 'Pest Control' },
  { key: 'truck', label: 'Delivery' },
  { key: 'shield', label: 'Security' },
  { key: 'key', label: 'Access' },
  { key: 'lock', label: 'Lock' },
  { key: 'wifi', label: 'Technology' },
  { key: 'trash', label: 'Waste' },
  { key: 'package', label: 'Supplies' },
  { key: 'warehouse', label: 'Storage' },
  { key: 'building', label: 'Building' },
  { key: 'home', label: 'Property' },
  { key: 'star', label: 'Premium' },
  { key: 'heart', label: 'Guest Care' },
  { key: 'folder', label: 'General' },
];

// Helper to get icon component with fallback
export function getDepartmentIcon(iconKey?: string | null): LucideIcon {
  return DEPARTMENT_ICON_MAP[iconKey || 'folder'] || Folder;
}
