/**
 * Render the exact fixed payload the ops agent receives — system prompt +
 * serialized tool catalog — as a markdown file to read alongside the code.
 *
 * Everything comes from the REAL builders (buildSystemPrompt,
 * toAnthropicTools), so the output is never a hand-transcribed copy that can
 * drift from what the model actually sees.
 *
 * The prompt is split into `## NN. Section` headings so VS Code's outline
 * (Ctrl+Shift+O) navigates it — the sections are the same ones core.ts writes,
 * detected by their trailing-colon header lines.
 *
 *   npm run prompt         → write docs/agent-prompt.md once
 *   npm run prompt:watch   → rewrite it on every save to the prompt/tool files
 *   npx tsx scripts/dumpAgentPayload.mts <outfile> [web|slack]
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { buildSystemPrompt } from '@/src/agent/prompt/core';
import { WEB_SURFACE } from '@/src/agent/prompt/web';
import { SLACK_SURFACE } from '@/src/agent/prompt/slack';
import { toAnthropicTools } from '@/src/agent/tools';

const out = process.argv[2] ?? 'docs/agent-prompt.md';
// Which surface's toolset to render. The prompt is shown for both regardless.
const surface = (process.argv[3] === 'slack' ? 'slack' : 'web') as
  | 'web'
  | 'slack';

const ACTOR = {
  appUserId: '00000000-0000-4000-8000-000000000001',
  name: 'Billy Hale',
  role: 'superadmin' as const,
};

// Rough token estimate: chars / 3.6 is close enough for BPE English + JSON.
const tok = (s: string) => Math.round(s.length / 3.6);

const webPrompt = buildSystemPrompt('America/Los_Angeles', 'web', ACTOR);
const slackPrompt = buildSystemPrompt('America/Los_Angeles', 'slack', ACTOR);
const tools = toAnthropicTools(surface);
const toolsJson = JSON.stringify(tools);
const otherTools = toAnthropicTools(surface === 'web' ? 'slack' : 'web');
const surfaceOnly = otherTools
  .filter((o) => !tools.some((t) => t.name === o.name))
  .map((t) => t.name);

/**
 * Split the prompt on its own section headers: a non-indented, non-bullet line
 * ending in a colon. Text before the first header is the opening block.
 */
interface Section {
  title: string;
  body: string;
}
function splitSections(prompt: string): Section[] {
  const sections: Section[] = [];
  let title = 'Opening';
  let buf: string[] = [];
  const push = () => {
    const body = buf.join('\n').replace(/^\n+|\n+$/g, '');
    if (body || sections.length === 0) sections.push({ title, body });
  };
  // Everything from "Operational instincts:" on is the inlined skills block —
  // prose that happens to contain colon-ending sentences. Stop splitting there
  // so it stays one unit instead of fragmenting on false headers.
  let inSkills = false;
  for (const line of prompt.split('\n')) {
    const t = line.trim();
    const isHeader =
      !inSkills &&
      t.endsWith(':') &&
      t.length > 0 &&
      t.length < 70 &&
      !/^[-*\s]/.test(line);
    if (isHeader && t === 'Operational instincts:') inSkills = true;
    if (isHeader) {
      push();
      title = t.slice(0, -1);
      buf = [];
    } else {
      buf.push(line);
    }
  }
  push();
  return sections;
}

const sections = splitSections(webPrompt);

const lines: string[] = [];
const w = (s = '') => lines.push(s);

w('# Ops agent prompt');
w();
w(
  '> Generated by `npm run prompt` from `buildSystemPrompt` / `toAnthropicTools`.',
);
w('> Do not edit this file — edit `src/agent/prompt/` and regenerate.');
w();
w(`- System prompt (web): **${webPrompt.length.toLocaleString()}** chars, **~${tok(webPrompt).toLocaleString()}** tokens`);
w(`- System prompt (slack): **${slackPrompt.length.toLocaleString()}** chars, **~${tok(slackPrompt).toLocaleString()}** tokens`);
w(`- Tool catalog (${surface}): **${tools.length}** tools, **~${tok(toolsJson).toLocaleString()}** tokens`);
w(`- Fixed prefix every turn (${surface}): **~${(tok(webPrompt) + tok(toolsJson)).toLocaleString()}** tokens`);
w();

w('## Section weights');
w();
w('| # | Section | Chars | ~Tokens | Share |');
w('|---|---|---:|---:|---:|');
sections.forEach((s, i) => {
  const share = ((s.body.length / webPrompt.length) * 100).toFixed(1);
  w(
    `| ${i + 1} | ${s.title} | ${s.body.length.toLocaleString()} | ${tok(s.body).toLocaleString()} | ${share}% |`,
  );
});
w();
w('---');
w();
w('# System prompt — web surface');
w();
sections.forEach((s, i) => {
  const share = ((s.body.length / webPrompt.length) * 100).toFixed(1);
  w(`## ${i + 1}. ${s.title}`);
  w();
  w(`\`${s.body.length.toLocaleString()} chars · ~${tok(s.body).toLocaleString()} tok · ${share}%\``);
  w();
  w('```text');
  w(s.body);
  w('```');
  w();
});

w('---');
w();
w('# Surface divergence');
w();
w(
  'The only four slots where web and Slack differ. Everything above is shared, written once in `core.ts`.',
);
w();
for (const key of ['rendering', 'enumeration', 'confirmation', 'taskCreation'] as const) {
  w(`## slot: ${key}`);
  w();
  w('**web**');
  w();
  w('```text');
  w(WEB_SURFACE[key]);
  w('```');
  w();
  w('**slack**');
  w();
  w('```text');
  w(SLACK_SURFACE[key]);
  w('```');
  w();
}

w('---');
w();
w(`# Tool catalog — ${surface}`);
w();
if (surfaceOnly.length > 0) {
  w(
    `Not offered here (${surface === 'web' ? 'slack' : 'web'}-only): ${surfaceOnly.map((n) => `\`${n}\``).join(', ')}.`,
  );
  w();
}
w('| Tool | Desc chars | Schema chars | ~Tokens |');
w('|---|---:|---:|---:|');
const sized = tools
  .map((t) => ({
    name: t.name,
    desc: t.description.length,
    schema: JSON.stringify(t.input_schema).length,
    total: JSON.stringify(t).length,
  }))
  .sort((a, b) => b.total - a.total);
for (const s of sized) {
  w(
    `| \`${s.name}\` | ${s.desc.toLocaleString()} | ${s.schema.toLocaleString()} | ${Math.round(s.total / 3.6).toLocaleString()} |`,
  );
}
w(
  `| **total** | **${sized.reduce((n, s) => n + s.desc, 0).toLocaleString()}** | **${sized.reduce((n, s) => n + s.schema, 0).toLocaleString()}** | **${Math.round(sized.reduce((n, s) => n + s.total, 0) / 3.6).toLocaleString()}** |`,
);
w();
w('---');
w();
w('# Tool definitions, verbatim');
w();
w('Each tool exactly as serialized onto the wire: the name the model calls, the description it reads, the schema it must satisfy.');
w();
for (const [i, t] of tools.entries()) {
  w(`## ${i + 1}. \`${t.name}\``);
  w();
  w('```text');
  w(t.description);
  w('```');
  w();
  w('<details><summary>Input schema</summary>');
  w();
  w('```json');
  w(JSON.stringify(t.input_schema, null, 2));
  w('```');
  w();
  w('</details>');
  w();
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join('\n'), 'utf8');

const stamp = new Date().toLocaleTimeString();
console.log(
  `[${stamp}] wrote ${out} — ${sections.length} sections | prompt ~${tok(webPrompt)} tok | ${tools.length} tools ~${tok(toolsJson)} tok`,
);
